name: Good First Issue Template
description: Create a Good First Issue.
title: "[Good First Issue]: "
labels: ["Good First Issue"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this good first issue!

        ## 🆕🐥 First Timers Only

        This issue is reserved for people who have never contributed or have made minimal contributions to [Hiero Python SDK](https://hiero.org).
        We know that creating a pull request (PR) is a major barrier for new contributors.
        The goal of this issue and all other issues in [**find a good first issue**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahiero-ledger+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution to the Hiero Python SDK.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is the problem you are trying to solve?
      value: 
        ## 👾 Description of the issue

        EDIT THIS SECTION

        AT THIS SECTION YOU NEED TO DESCRIBE THE ISSUE IN A WAY THAT IS UNDERSTANDABLE TO NEW CONTRIBUTORS.
        YOU MUST NOT ASSUME THAT SUCH CONTRIBUTORS HAVE ANY KNOWLEDGE ABOUT THE CODEBASE OR HIERO.
        IT IS HELPFUL TO ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE SECTIONS.
    validations:
      required: true