name: Test Files Naming Check

on:
  pull_request:
    types: [opened, synchronize, review_requested]

permissions:
  contents: read

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-test-files:
    runs-on: ${{ (github.repository_owner != 'hiero-ledger') && 'ubuntu-latest' || 'hl-sdk-py-lin-md' }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout repository (shallow)
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 2 # Fetch at least 2 commits to compare changes in test files

      - name: Fetch main
        run: git fetch origin main --depth=1 # Ensure we have the latest main for accurate diff

      - name: Run test file naming check
        run: node .github/scripts/pr-check-test-files.js
